####################################################################
# SCRIPTS

#script:
  # triggering the opto coupler in order to switch the light bar off
  - id: lightbar_script_oc_trigger_on_off
    mode: single
    then:
      - logger.log: "The lightbar is now theoretically switched on/off. But as there is no action in the script lightbar_script_oc_trigger_on ..."

####################################################################
# EOF
####################################################################
