####################################################################
# color config for ESP32-2432S028R aka CYD --- with onboard ESP32
####################################################################

# color:

# Create a Home Assistant blue color
  - id: ha_blue
    hex: 51c0f2

# ############################################################
#  END OF FILE
# ############################################################
