####################################################################
# TOUCHSCREEN
#
# configuration for TFT 2.8" touch panel (240x320 RGB)
# for details see https://esphome.io/components/display/ili9xxx.html (obsolete) and
# https://esphome.io/components/display/mipi_spi.html (new since ESPHome v2024.6)
# touchscreen:
  - platform: xpt2046
    display: ${display_id}
    cs_pin: GPIO33      # Chip Select pin
    calibration:
      x_min: 300
      x_max: 3900
      y_min: 200
      y_max: 3700
    on_touch:
      - lambda: |-
            ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                touch.x,
                touch.y,
                touch.x_raw,
                touch.y_raw
                );
    # on_touch:
    #   then:
    #     ...
    # on_update:
    #   then:
    #     ...
    # on_release:
    #   then:
####################################################################
# EOF
####################################################################
