####################################################################
# I2C config for ESP32-2432S028R aka CYD --- with onboard ESP32
####################################################################

# for details see https://esphome.io/components/i2c.html
# i2c:
  id: !secret I2C_BUS_A
  scl: !secret I2C_SCL_PIN_ESP32_2432S028R_CYD_V1
  sda: !secret I2C_SDA_PIN_ESP32_2432S028R_CYD_V1
  scan: true

  # default values
  # see: https://esphome.io/components/i2c.html#configuration-variables
  # frequency: Set the frequency the I²C bus should operate on. Defaults to 50kHz. Values are 50kHz, 100kHz, 200kHz, … 800kHz

# ############################################################
#  END OF FILE
# ############################################################

