####################################################################
# DISPLAY INTERVAL

# update time and display it every x interval
  - interval: 20s
    then:
      - display.page.show_next: ${display_id}
      - component.update: ${display_id}

# ############################################################
#  END OF FILE
# ############################################################
