- "\U000F0502" # television
- "\U000F0335" # lightbulb
- "\U000F06E8" # lightbult-on
- "\U000F0336" # lightbulb-outline
- "\U000F1253" # lightbulb-group
- "\U000F1254" # lightbulb-group-outline
- "\U000F075D" # volume-plus
- "\U000F075E" # volume-minus
- "\U000F0141" # chevron-left
- "\U000F0142" # chevron-right
- "\U000F0140" # chevron-down
- "\U000F02DC" # home
- "\U000F0425" # power
- "\U000F01D8" # dots-horizontal
- "\U000F040E" # play-pause
- "\U000F04DB" # stop
- "\U000F042B" # printer-3d
- "\U000F0E5B" # printer-3d-nozzle
- "\U000F02E3" # bed
- "\U000F1576" # lamps
- "\U000F04B9" # sofa
- "\U000F0D80" # home-floor-1
- "\U000F0D81" # home-floor-2
- "\U000F0F9B" # home-export-outline