####################################################################
# WIFI - multiple networks
####################################################################

# ---------------------------------------------------------------------
# WiFi settings
wifi:
  networks:
    - ssid: !secret WIFI_L0_SSID
      password: !secret WIFI_L0_PW
    - ssid: !secret WIFI_L2_SSID
      password: !secret WIFI_L2_PW
    - ssid: !secret WIFI_L91_SSID
      password: !secret WIFI_L91_PW
    - ssid: !secret WIFI_L92_SSID
      password: !secret WIFI_L92_PW
  domain: !secret WIFI_DOMAIN
  min_auth_mode: WPA2  # Reject WPA-only networks
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret ap_password

# renaming a device which is online
# see https://esphome.io/components/esphome.html?highlight=restore_from#changing-esphome-node-name
# put the current device name in the next line and uncomment, compile/upload and comment the next line again
#  use_address: test8266.local

# now defaults (just to mention them)
#  reboot_timeout: !secret WIFI_REBOOT_TIMEOUT
#  output_power: !secret WIFI_OUTPUT_POWER_STD
#  fast_connect: !secret WIFI_FAST_CONNECT
#  id: !secret WIFI_ID (rather not use this without susbstitution in place!)

# ############################################################
#  END OF FILE
# ############################################################
