# ############################################################
#
#  Binary sensors
#
# ############################################################

#binary_sensor:

###########################################################################
# import sensor from home assistant
###########################################################################
- platform: homeassistant
  name: "L2 Kitchen12 coffeemachine Sensor"
  id: widget_sensor_coffeemachine
  entity_id: switch.zb_plug_l2_kitchen_coffeemachine
  # trigger_on_initial_state: true
  publish_initial_state: true
  on_state:
    - if:
        condition:
          - binary_sensor.is_on: widget_sensor_coffeemachine
        then:
          - lvgl.widget.update:
              id: lbl_btn_coffeemachine
              text_color: default_btn_txt_checked_color
        else:
          - lvgl.widget.update:
              id: lbl_btn_coffeemachine
              text_color: default_btn_txt_color
# ############################################################
#  END OF FILE
# ############################################################
