####################################################################
# DEVICE SPECIFIC SUBSTITUTIONS

# device definitions
device_name: l2kitchen11
device_comment: Level 2 Kitchen D11 ESP32-2432S028R aka CYD
device_area: L2

device_platform: ESP32
wifi_static_ip: 192.168.178.226

# The ESP32-2432S028R uses a standard ESP32-WROVER, 
# so we use the esp32dev defintion here with the Arduino framework
device_board: esp32dev
device_framework: arduino

# the friendly name and id
friendly_name: ""
friendly_id: ""

# display
display_id: ${device_name}_display

# # DALLAS sensors
# # details for DALLAS sensors connected to the device
# dallas_01c01_name: $friendly_name TempCase 01
# dallas_01c01_address: !secret DALLAS_01_L2_KITCHEN_ESP32_CASESENSOR_01_ADDRESS
# dallas_01e01_name: $friendly_name TempEnv 01
# dallas_01e01_address: !secret DALLAS_01_L2_KITCHEN_ESP32_ENVSENSOR_01_ADDRESS
####################################################################
# EOF
####################################################################
